# Lint and analyzer settings for vvk_ui_kit.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - comment_references
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_relative_imports

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    public_member_api_docs: warning
